export const Apartments = [
  {
    id: 1,
    title: "Skyline Residences Studio",
    price: "₱18,500",
    location: "Lahug, Cebu City",
    district: "Cebu IT Park",
    unitType: "Condo",
    landmarks: ["Skyline Residences", "Ayala Center Cebu"],
    tags: ["1 Bedroom, 1 Bath", "Fiber WiFi"],
    image: "https://picsum.photos/seed/studio-cebu/600/400",
    furnishing: "Full Furnished",
    description:
      "A compact and fully furnished studio unit at One Oasis by Cebu Landmasters. Features a modern pantry-style kitchen, queen-sized Murphy bed, and access to resort-style amenities. Ideal for single professionals working in the Cebu north corridor.",
    beds: 1,
    baths: 1,
    sqm: 30,
    amenities: [
      { name: "High-speed WiFi", icon: "Wifi" },
      { name: "Air Conditioning", icon: "Aircon" },
      { name: "Gym Access", icon: "Gym" },
      { name: "24/7 Security", icon: "Security" },
    ],
    detailedImages: [
      "https://picsum.photos/seed/skyline-loft-main/1200/800",
      "https://picsum.photos/seed/skyline-loft-kitchen/600/400",
      "https://picsum.photos/seed/skyline-loft-bed/600/400",
      "https://picsum.photos/seed/skyline-loft-bath/600/400",
      "https://picsum.photos/seed/skyline-loft-pool/600/400",
    ],
    landlord: {
      name: "Engr. Rafael Santos",
      title: "Verified Landlord",
      rating: 4.9,
      reviewCount: 47,
      responseTime: "Under 1 hour",
      memberSince: "May 2021",
      avatar: "https://picsum.photos/seed/landlord-rafael/200/200",
    },
    savedDaysAgo: 2,
  },
  {
    id: 2,
    title: "IT Park Loft Unit",
    price: "₱22,000",
    location: "Lahug, Cebu City",
    district: "Cebu IT Park",
    unitType: "Loft",
    landmarks: ["IT Park", "eBloc Tower"],
    tags: ["1 Bedroom, 1 Bath", "Parking", "Gym"],
    image: "https://picsum.photos/seed/itpark-loft/600/400",
    furnishing: "Full Furnished",
    description:
      "A compact and fully furnished studio unit at One Oasis by Cebu Landmasters. Features a modern pantry-style kitchen, queen-sized Murphy bed, and access to resort-style amenities. Ideal for single professionals working in the Cebu north corridor.",
    beds: 1,
    baths: 1,
    sqm: 30,
    amenities: [
      { name: "High-speed WiFi", icon: "Wifi" },
      { name: "Air Conditioning", icon: "Aircon" },
      { name: "Gym Access", icon: "Gym" },
      { name: "24/7 Security", icon: "Security" },
    ],
    detailedImages: [
      "https://picsum.photos/seed/itpark-loft-main/1200/800",
      "https://picsum.photos/seed/itpark-loft-kitchen/600/400",
      "https://picsum.photos/seed/itpark-loft-bed/600/400",
      "https://picsum.photos/seed/itpark-loft-bath/600/400",
      "https://picsum.photos/seed/itpark-loft-pool/600/400",
    ],
    landlord: {
      name: "Engr. Rafael Santos",
      title: "Verified Landlord",
      rating: 4.9,
      reviewCount: 47,
      responseTime: "Under 1 hour",
      memberSince: "May 2021",
      avatar: "https://picsum.photos/seed/landlord-rafael/200/200",
    },
        savedDaysAgo: 2,

  },
  {
    id: 3,
    title: "IT Park Studio Pad",
    price: "₱14,000",
    location: "Lahug, Cebu City",
    district: "Cebu IT Park",
    unitType: "Studio",
    landmarks: ["IT Park", "Sugbo Mercado"],
    tags: ["Studio Unit", "1 Bath", "Fiber WiFi"],
    image: "https://picsum.photos/seed/itpark-studio/600/400",
    furnishing: "Full Furnished",
    description:
      "A compact and fully furnished studio unit at One Oasis by Cebu Landmasters. Features a modern pantry-style kitchen, queen-sized Murphy bed, and access to resort-style amenities. Ideal for single professionals working in the Cebu north corridor.",
    beds: 1,
    baths: 1,
    sqm: 30,
    amenities: [
      { name: "High-speed WiFi", icon: "Wifi" },
      { name: "Air Conditioning", icon: "Aircon" },
    ],
    detailedImages: [
      "https://picsum.photos/seed/itpark-studio-main/1200/800",
      "https://picsum.photos/seed/itpark-studio-kitchen/600/400",
      "https://picsum.photos/seed/itpark-studio-bed/600/400",
      "https://picsum.photos/seed/itpark-studio-bath/600/400",
      "https://picsum.photos/seed/itpark-studio-pool/600/400",
    ],
    landlord: {
      name: "Engr. Rafael Santos",
      title: "Verified Landlord",
      rating: 4.9,
      reviewCount: 47,
      responseTime: "Under 1 hour",
      memberSince: "May 2021",
      avatar: "https://picsum.photos/seed/landlord-rafael/200/200",
    },
    savedDaysAgo: 2,
  },
  {
    id: 4,
    title: "Cebu Business Park Suite",
    price: "₱35,000",
    location: "Cebu Business Park, Cebu City",
    district: "Cebu Business Park",
    unitType: "Apartment",
    landmarks: ["Cebu Business Park", "SM City Cebu"],
    tags: ["2 Bedrooms, 2 Baths", "Pool", "Concierge"],
    image: "https://picsum.photos/seed/cbp-suite/600/400",
    furnishing: "Full Furnished",
    description:
      "A compact and fully furnished studio unit at One Oasis by Cebu Landmasters. Features a modern pantry-style kitchen, queen-sized Murphy bed, and access to resort-style amenities. Ideal for single professionals working in the Cebu north corridor.",
    beds: 2,
    baths: 2,
    sqm: 90,
    amenities: [
      { name: "High-speed WiFi", icon: "Wifi" },
      { name: "Air Conditioning", icon: "Aircon" },
      { name: "Gym Access", icon: "Gym" },
      { name: "24/7 Security", icon: "Security" },
    ],
    detailedImages: [
      "https://picsum.photos/seed/cbp-suite-main/1200/800",
      "https://picsum.photos/seed/cbp-suite-kitchen/600/400",
      "https://picsum.photos/seed/cbp-suite-bed/600/400",
      "https://picsum.photos/seed/cbp-suite-bath/600/400",
      "https://picsum.photos/seed/cbp-suite-pool/600/400",
    ],
    savedDaysAgo: 2,
    landlord: {
      name: "Engr. Rafael Santos",
      title: "Verified Landlord",
      rating: 4.9,
      reviewCount: 47,
      responseTime: "Under 1 hour",
      memberSince: "May 2021",
      avatar: "https://picsum.photos/seed/landlord-rafael/200/200",
    }
  },
  {
    id: 5,
    title: "Fuente Studio Pad",
    price: "₱9,500",
    location: "Fuente Osmeña, Cebu City",
    district: "Cebu Business Park",
    unitType: "Studio",
    landmarks: ["Fuente Osmeña Circle", "Cebu Provincial Capitol"],
    tags: ["Studio Unit", "1 Bath", "Fiber WiFi"],
    image: "https://picsum.photos/seed/fuente-pad/600/400",
    furnishing: "Full Furnished",
    description:
      "A compact and fully furnished studio unit at One Oasis by Cebu Landmasters. Features a modern pantry-style kitchen, queen-sized Murphy bed, and access to resort-style amenities. Ideal for single professionals working in the Cebu north corridor.",
    beds: 1,
    baths: 1,
    sqm: 30,
    amenities: [
      { name: "High-speed WiFi", icon: "Wifi" },
      { name: "Air Conditioning", icon: "Aircon" },
      { name: "Gym Access", icon: "Gym" },
      { name: "24/7 Security", icon: "Security" },
    ],
    detailedImages: [
      "https://picsum.photos/seed/fuente-studio-main/1200/800",
      "https://picsum.photos/seed/fuente-studio-kitchen/600/400",
      "https://picsum.photos/seed/fuente-studio-bed/600/400",
      "https://picsum.photos/seed/fuente-studio-bath/600/400",
      "https://picsum.photos/seed/fuente-studio-pool/600/400",
    ],
    landlord: {
      name: "Engr. Rafael Santos",
      title: "Verified Landlord",
      rating: 4.9,
      reviewCount: 47,
      responseTime: "Under 1 hour",
      memberSince: "May 2021",
      avatar: "https://picsum.photos/seed/landlord-rafael/200/200",
    },
    savedDaysAgo: 2,
  },
  {
    id: 6,
    title: "Mandaue Riverside Condo",
    price: "₱15,000",
    location: "Cebu Business Park, Cebu City",
    district: "Cebu Business Park",
    unitType: "Condo",
    landmarks: ["SM City Cebu", "Ayala Center Cebu"],
    tags: ["1 Bedroom, 1 Bath", "River View", "Aircon"],
    image: "https://picsum.photos/seed/mandaue-condo/600/400",
    furnishing: "Full Furnished",
    description:
      "A compact and fully furnished studio unit at One Oasis by Cebu Landmasters. Features a modern pantry-style kitchen, queen-sized Murphy bed, and access to resort-style amenities. Ideal for single professionals working in the Cebu north corridor.",
    beds: 1,
    baths: 1,
    sqm: 30,
    amenities: [
      { name: "High-speed WiFi", icon: "Wifi" },
      { name: "Air Conditioning", icon: "Aircon" },
      { name: "Gym Access", icon: "Gym" },
      { name: "24/7 Security", icon: "Security" },
    ],
    detailedImages: [
      "https://picsum.photos/seed/mandaue-condo-main/1200/800",
      "https://picsum.photos/seed/mandaue-condo-kitchen/600/400",
      "https://picsum.photos/seed/mandaue-condo-bed/600/400",
      "https://picsum.photos/seed/mandaue-condo-bath/600/400",
      "https://picsum.photos/seed/mandaue-condo-pool/600/400",
    ],
    landlord: {
      name: "Engr. Rafael Santos",
      title: "Verified Landlord",
      rating: 4.9,
      reviewCount: 47,
      responseTime: "Under 1 hour",
      memberSince: "May 2021",
      avatar: "https://picsum.photos/seed/landlord-rafael/200/200",
    },
    savedDaysAgo: 2,
  },
  {
    id: 7,
    title: "Colon Heritage Flat",
    price: "₱6,500",
    location: "Colon Street, Cebu City",
    district: "Colon Street",
    unitType: "Apartment",
    landmarks: ["Colon Street", "Carbon Market"],
    tags: ["Studio Unit", "1 Bath", "Near Market"],
    image: "https://picsum.photos/seed/colon-flat/600/400",
    furnishing: "Full Furnished",
    description:
      "A compact and fully furnished studio unit at One Oasis by Cebu Landmasters. Features a modern pantry-style kitchen, queen-sized Murphy bed, and access to resort-style amenities. Ideal for single professionals working in the Cebu north corridor.",
    beds: 1,
    baths: 1,
    sqm: 30,
    amenities: [
      { name: "High-speed WiFi", icon: "Wifi" },
      { name: "Air Conditioning", icon: "Aircon" },
    ],
    detailedImages: [
      "https://picsum.photos/seed/colon-flat-main/1200/800",
      "https://picsum.photos/seed/colon-flat-kitchen/600/400",
      "https://picsum.photos/seed/colon-flat-bed/600/400",
      "https://picsum.photos/seed/colon-flat-bath/600/400",
      "https://picsum.photos/seed/colon-flat-pool/600/400",
    ],
    landlord: {
      name: "Engr. Rafael Santos",
      title: "Verified Landlord",
      rating: 4.9,
      reviewCount: 47,
      responseTime: "Under 1 hour",
      memberSince: "May 2021",
      avatar: "https://picsum.photos/seed/landlord-rafael/200/200",
    },
    savedDaysAgo: 2,
  },
  {
    id: 8,
    title: "Colon Bedspace Room",
    price: "₱4,500",
    location: "Colon Street, Cebu City",
    district: "Colon Street",
    unitType: "Bedspace",
    landmarks: ["Colon Street", "Basilica del Santo Niño"],
    tags: ["Bedspace", "Shared Bath", "Near Church"],
    image: "https://picsum.photos/seed/colon-bedspace/600/400",
    furnishing: "Full Furnished",
    description:
      "A compact and fully furnished studio unit at One Oasis by Cebu Landmasters. Features a modern pantry-style kitchen, queen-sized Murphy bed, and access to resort-style amenities. Ideal for single professionals working in the Cebu north corridor.",
    beds: 1,
    baths: 1,
    sqm: 20,
    amenities: [
      { name: "High-speed WiFi", icon: "Wifi" },
    ],
    detailedImages: [
      "https://picsum.photos/seed/colon-bedspace-main/1200/800",
      "https://picsum.photos/seed/colon-bedspace-kitchen/600/400",
      "https://picsum.photos/seed/colon-bedspace-bed/600/400",
      "https://picsum.photos/seed/colon-bedspace-bath/600/400",
      "https://picsum.photos/seed/colon-bedspace-pool/600/400",
    ],
    landlord: {
      name: "Engr. Rafael Santos",
      title: "Verified Landlord",
      rating: 4.9,
      reviewCount: 47,
      responseTime: "Under 1 hour",
      memberSince: "May 2021",
      avatar: "https://picsum.photos/seed/landlord-rafael/200/200",
    },
    savedDaysAgo: 2,
  },
  {
    id: 9,
    title: "Colon Studio Unit",
    price: "₱8,000",
    location: "Colon Street, Cebu City",
    district: "Colon Street",
    unitType: "Studio",
    landmarks: ["Colon Street", "Fuente Osmeña Circle"],
    tags: ["Studio Unit", "1 Bath", "Aircon"],
    image: "https://picsum.photos/seed/colon-studio/600/400",
    furnishing: "Full Furnished",
    description:
      "A compact and fully furnished studio unit at One Oasis by Cebu Landmasters. Features a modern pantry-style kitchen, queen-sized Murphy bed, and access to resort-style amenities. Ideal for single professionals working in the Cebu north corridor.",
    beds: 1,
    baths: 1,
    sqm: 30,
    amenities: [
      { name: "High-speed WiFi", icon: "Wifi" },
      { name: "Air Conditioning", icon: "Aircon" },
    ],
    detailedImages: [
      "https://picsum.photos/seed/colon-studio-main/1200/800",
      "https://picsum.photos/seed/colon-studio-kitchen/600/400",
      "https://picsum.photos/seed/colon-studio-bed/600/400",
      "https://picsum.photos/seed/colon-studio-bath/600/400",
      "https://picsum.photos/seed/colon-studio-pool/600/400",
    ],
    landlord: {
      name: "Engr. Rafael Santos",
      title: "Verified Landlord",
      rating: 4.9,
      reviewCount: 47,
      responseTime: "Under 1 hour",
      memberSince: "May 2021",
      avatar: "https://picsum.photos/seed/landlord-rafael/200/200",
    },
    savedDaysAgo: 2,
  },
  {
    id: 10,
    title: "Paseo Arcenas Garden Unit",
    price: "₱19,000",
    location: "Nivel Hills, Cebu City",
    district: "Paseo Arcenas",
    unitType: "Apartment",
    landmarks: ["Paseo Arcenas", "Nivel Hills"],
    tags: ["2 Bedrooms, 1 Bath", "Garden View", "Parking"],
    image: "https://picsum.photos/seed/paseo-garden/600/400",
    furnishing: "Full Furnished",
    description:
      "A compact and fully furnished studio unit at One Oasis by Cebu Landmasters. Features a modern pantry-style kitchen, queen-sized Murphy bed, and access to resort-style amenities. Ideal for single professionals working in the Cebu north corridor.",
    beds: 2,
    baths: 1,
    sqm: 60,
    amenities: [
      { name: "High-speed WiFi", icon: "Wifi" },
      { name: "Air Conditioning", icon: "Aircon" },
      { name: "Gym Access", icon: "Gym" },
      { name: "24/7 Security", icon: "Security" },
    ],
    detailedImages: [
      "https://picsum.photos/seed/paseo-garden-main/1200/800",
      "https://picsum.photos/seed/paseo-garden-kitchen/600/400",
      "https://picsum.photos/seed/paseo-garden-bed/600/400",
      "https://picsum.photos/seed/paseo-garden-bath/600/400",
      "https://picsum.photos/seed/paseo-garden-pool/600/400",
    ],
    landlord: {
      name: "Engr. Rafael Santos",
      title: "Verified Landlord",
      rating: 4.9,
      reviewCount: 47,
      responseTime: "Under 1 hour",
      memberSince: "May 2021",
      avatar: "https://picsum.photos/seed/landlord-rafael/200/200",
    },
    savedDaysAgo: 2,
  },
  {
    id: 11,
    title: "Paseo Studio Condo",
    price: "₱12,500",
    location: "Nivel Hills, Cebu City",
    district: "Paseo Arcenas",
    unitType: "Condo",
    landmarks: ["Paseo Arcenas", "Banilad Town Center"],
    tags: ["Studio Unit", "1 Bath", "Pool", "Gym"],
    image: "https://picsum.photos/seed/paseo-studio/600/400",
    furnishing: "Full Furnished",
    description:
      "A compact and fully furnished studio unit at One Oasis by Cebu Landmasters. Features a modern pantry-style kitchen, queen-sized Murphy bed, and access to resort-style amenities. Ideal for single professionals working in the Cebu north corridor.",
    beds: 1,
    baths: 1,
    sqm: 30,
    amenities: [
      { name: "High-speed WiFi", icon: "Wifi" },
      { name: "Air Conditioning", icon: "Aircon" },
      { name: "Pool Access", icon: "swimming-pool" },
      { name: "Gym Access", icon: "Gym" },
    ],
    detailedImages: [
      "https://picsum.photos/seed/skyline-loft-main/1200/800",
      "https://picsum.photos/seed/skyline-loft-kitchen/600/400",
      "https://picsum.photos/seed/skyline-loft-bed/600/400",
      "https://picsum.photos/seed/skyline-loft-bath/600/400",
      "https://picsum.photos/seed/skyline-loft-pool/600/400",
    ],
    landlord: {
      name: "Engr. Rafael Santos",
      title: "Verified Landlord",
      rating: 4.9,
      reviewCount: 47,
      responseTime: "Under 1 hour",
      memberSince: "May 2021",
      avatar: "https://picsum.photos/seed/landlord-rafael/200/200",
    },
    savedDaysAgo: 2,
  },
  {
    id: 12,
    title: "Paseo Loft Residences",
    price: "₱26,000",
    location: "Nivel Hills, Cebu City",
    district: "Paseo Arcenas",
    unitType: "Loft",
    landmarks: ["Paseo Arcenas", "Gaisano Country Mall"],
    tags: ["1 Bedroom, 1 Bath", "City View", "Fiber WiFi"],
    image: "https://picsum.photos/seed/paseo-loft/600/400",
    furnishing: "Full Furnished",
    description:
      "A compact and fully furnished studio unit at One Oasis by Cebu Landmasters. Features a modern pantry-style kitchen, queen-sized Murphy bed, and access to resort-style amenities. Ideal for single professionals working in the Cebu north corridor.",
    beds: 1,
    baths: 1,
    sqm: 30,
    amenities: [
      { name: "High-speed WiFi", icon: "Wifi" },
      { name: "Air Conditioning", icon: "Aircon" },
      { name: "Pool Access", icon: "swimming-pool" },
      { name: "Gym Access", icon: "Gym" },
    ],
    detailedImages: [
      "https://picsum.photos/seed/skyline-loft-main/1200/800",
      "https://picsum.photos/seed/skyline-loft-kitchen/600/400",
      "https://picsum.photos/seed/skyline-loft-bed/600/400",
      "https://picsum.photos/seed/skyline-loft-bath/600/400",
      "https://picsum.photos/seed/skyline-loft-pool/600/400",
    ],
    landlord: {
      name: "Engr. Rafael Santos",
      title: "Verified Landlord",
      rating: 4.9,
      reviewCount: 47,
      responseTime: "Under 1 hour",
      memberSince: "May 2021",
      avatar: "https://picsum.photos/seed/landlord-rafael/200/200",
    },
    savedDaysAgo: 2,
  },
];


export const ALL_LISTINGS = Apartments.map((a) => ({
  ...a,
  price: Number(a.price.replace(/[₱,]/g, "")),
  amenities: a.amenities.map((amenity) => amenity.name),
}));

/** Listings keyed by string id for the detail page. */
export const LISTINGS = Object.fromEntries(
  Apartments.map((a) => [
    String(a.id),
    {
      ...a,
      price: Number(a.price.replace(/[₱,]/g, "")),
      unit: a.unitType,
      images: a.detailedImages ?? [a.image],
      priceSuffix: null,
      landlord: a.landlord ?? null,
    },
  ])
);